In [4]:
import numpy
n = numpy.arange(27)

In [13]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [18]:
m=numpy.asarray([[123,12,123,123,12],[],[]])
m

array([[123, 12, 123, 123, 12], [], []], dtype=object)

In [20]:
import cv2

In [29]:
im_g=cv2.imread("smallgray.png", 0)
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [30]:
im_g.T

array([[187, 198, 209],
       [158, 125, 134],
       [104, 255, 255],
       [121, 255,  97],
       [143, 147, 182]], dtype=uint8)

In [32]:
cv2.imwrite('newsmallgray.png', im_g.T)

True

In [37]:
im_g[0:, 2:4]

array([[104, 121],
       [255, 255],
       [255,  97]], dtype=uint8)

In [43]:
for i in im_g.flat:
    print (i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [49]:
ims=numpy.hstack((im_g, im_g, im_g))

In [51]:
ims=numpy.vstack((im_g, im_g, im_g))
ims

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [54]:
lst = numpy.vsplit(ims, 3)
lst

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]